import React,{useEffect,useMemo,useState} from 'react';
import {Clapperboard,Film,Link,Plus,RotateCcw,Save,Trash2} from 'lucide-react';
import {useNotflix} from '../context/NotflixContext.jsx';
import FocusButton from './FocusButton.jsx';
import SeriesStudio from './SeriesStudio.jsx';

const empty={title:'',type:'movie',emoji:'🎬',tagline:'',description:'',genres:'Comedy',rating:'PG-13',runtime:'1h 30m',tone:'midnight',source:'',trailer:'',poster:'',backdrop:''};
const emptyMedia={source:'',trailer:'',poster:'',backdrop:'',subtitleUrl:'',introEnd:''};
export default function ContentStudio(){
  const{catalog,customTitles,createCustomTitle,removeCustomTitle,updateTitleContent,clearTitleContent,contentOverrides,notify}=useNotflix();
  const[form,setForm]=useState(empty);const[mediaTitleId,setMediaTitleId]=useState('pop');const[mediaForm,setMediaForm]=useState(emptyMedia);
  const selected=useMemo(()=>catalog.find((item)=>item.id===mediaTitleId)??catalog[0],[catalog,mediaTitleId]);
  useEffect(()=>{if(!selected)return;const media=selected.media||{};setMediaForm({source:media.source||'',trailer:media.trailer||'',poster:media.poster||'',backdrop:media.backdrop||'',subtitleUrl:media.subtitles?.[0]?.src||'',introEnd:media.introEnd||''});},[selected?.id]);
  const patch=(key,value)=>setForm((prev)=>({...prev,[key]:value}));const patchMedia=(key,value)=>setMediaForm((prev)=>({...prev,[key]:value}));
  const submit=(event)=>{event.preventDefault();if(!form.title.trim())return;const created=createCustomTitle(form);setForm(empty);setMediaTitleId(created.id);notify(`${created.title} added to NOTFLIX`);};
  const saveMedia=(event)=>{event.preventDefault();if(!selected)return;updateTitleContent(selected.id,{media:{source:mediaForm.source.trim(),trailer:mediaForm.trailer.trim(),poster:mediaForm.poster.trim(),backdrop:mediaForm.backdrop.trim(),subtitles:mediaForm.subtitleUrl.trim()?[{lang:'en',label:'English',src:mediaForm.subtitleUrl.trim()}]:[],introEnd:Number(mediaForm.introEnd)||0}});notify(`${selected.title} media updated`);};
  const readiness=useMemo(()=>catalog.reduce((acc,item)=>{const media=item.media||{};acc.total+=1;if(media.poster)acc.poster+=1;if(media.backdrop)acc.backdrop+=1;if(media.trailer)acc.trailer+=1;if(media.source)acc.full+=1;return acc;},{total:0,poster:0,backdrop:0,trailer:0,full:0}),[catalog]);
  return <div className="studio">
    <div className="studio__intro"><Clapperboard/><div><h3>Catalog Studio</h3><p>Create titles and attach finished generated media without changing application code.</p></div></div>
    <div className="readiness-strip"><div><strong>{readiness.total}</strong><span>Titles</span></div><div><strong>{readiness.poster}</strong><span>Posters</span></div><div><strong>{readiness.backdrop}</strong><span>Backdrops</span></div><div><strong>{readiness.trailer}</strong><span>Trailers</span></div><div><strong>{readiness.full}</strong><span>Full films</span></div></div>
    <details className="studio-section" open><summary><Plus size={16}/> Create a new title</summary><form className="studio-form" onSubmit={submit}>
      <label><span>Title</span><input value={form.title} onChange={(e)=>patch('title',e.target.value)} placeholder="POP 2: POP HARDER"/></label><label><span>Type</span><select value={form.type} onChange={(e)=>patch('type',e.target.value)}><option value="movie">Movie</option><option value="show">Show</option></select></label><label><span>Emoji</span><input value={form.emoji} onChange={(e)=>patch('emoji',e.target.value)} maxLength={4}/></label><label className="studio-form__wide"><span>Tagline</span><input value={form.tagline} onChange={(e)=>patch('tagline',e.target.value)} placeholder="One sentence of extremely serious nonsense."/></label><label className="studio-form__wide"><span>Description</span><textarea value={form.description} onChange={(e)=>patch('description',e.target.value)} rows={3}/></label><label><span>Genres</span><input value={form.genres} onChange={(e)=>patch('genres',e.target.value)} placeholder="Comedy, Adventure"/></label><label><span>Rating</span><input value={form.rating} onChange={(e)=>patch('rating',e.target.value)}/></label><label><span>Runtime</span><input value={form.runtime} onChange={(e)=>patch('runtime',e.target.value)}/></label><label><span>Art tone</span><input value={form.tone} onChange={(e)=>patch('tone',e.target.value)}/></label><label className="studio-form__wide"><span><Link size={14}/> Full video URL</span><input value={form.source} onChange={(e)=>patch('source',e.target.value)} placeholder="https://...mp4"/></label><label className="studio-form__wide"><span><Link size={14}/> Trailer URL</span><input value={form.trailer} onChange={(e)=>patch('trailer',e.target.value)} placeholder="https://...mp4"/></label><label><span>Poster URL</span><input value={form.poster} onChange={(e)=>patch('poster',e.target.value)}/></label><label><span>Backdrop URL</span><input value={form.backdrop} onChange={(e)=>patch('backdrop',e.target.value)}/></label><FocusButton className="hq-send studio-form__submit" type="submit"><Plus size={18}/> Add title</FocusButton>
    </form></details>
    <details className="studio-section" open><summary><Film size={16}/> Attach / replace media</summary><form className="studio-form" onSubmit={saveMedia}><label className="studio-form__wide"><span>Catalog title</span><select value={selected?.id||''} onChange={(e)=>setMediaTitleId(e.target.value)}>{catalog.map((item)=><option value={item.id} key={item.id}>{item.title}</option>)}</select></label><label className="studio-form__wide"><span><Link size={14}/> Full movie video URL</span><input value={mediaForm.source} onChange={(e)=>patchMedia('source',e.target.value)} placeholder="https://...mp4"/></label><label className="studio-form__wide"><span><Link size={14}/> Trailer URL</span><input value={mediaForm.trailer} onChange={(e)=>patchMedia('trailer',e.target.value)} placeholder="https://...mp4"/></label><label><span>Poster image URL</span><input value={mediaForm.poster} onChange={(e)=>patchMedia('poster',e.target.value)}/></label><label><span>Backdrop image URL</span><input value={mediaForm.backdrop} onChange={(e)=>patchMedia('backdrop',e.target.value)}/></label><label><span>English VTT subtitles URL</span><input value={mediaForm.subtitleUrl} onChange={(e)=>patchMedia('subtitleUrl',e.target.value)}/></label><label><span>Intro ends at (seconds)</span><input type="number" min="0" value={mediaForm.introEnd} onChange={(e)=>patchMedia('introEnd',e.target.value)}/></label><div className="studio-form__submit studio-media-actions"><FocusButton className="hq-send" type="submit"><Save size={17}/> Save media</FocusButton>{contentOverrides[selected?.id]&&<FocusButton className="settings-action" type="button" onClick={()=>{clearTitleContent(selected.id);notify(`${selected.title} restored to built-in media`);}}><RotateCcw size={17}/> Reset overrides</FocusButton>}</div></form></details>
    <SeriesStudio/>
    <div className="studio-library"><h4>Custom titles</h4>{customTitles.length===0?<p className="studio-empty">Nothing custom yet. The built-in catalog is carrying civilization.</p>:customTitles.map((item)=><div className="studio-title" key={item.id}><span>{item.emoji}</span><div><strong>{item.title}</strong><small>{item.type} · {item.media?.source?'full media attached':'simulated playback'}</small></div><FocusButton onClick={()=>removeCustomTitle(item.id)} aria-label={`Remove ${item.title}`}><Trash2 size={17}/></FocusButton></div>)}</div>
  </div>;
}
