import React,{useMemo,useState} from 'react';
import {Activity,Cast,Clapperboard,Eye,Pause,Play,RadioTower,Search,Send,SkipBack,SkipForward,Sparkles,X} from 'lucide-react';
import {controlBus} from '../lib/controlBus.js';
import {PRANKS} from '../lib/prankEngine.js';
import {useNotflix} from '../context/NotflixContext.jsx';
import Brand from './Brand.jsx';
import FocusButton from './FocusButton.jsx';
import ContentStudio from './ContentStudio.jsx';
import PrankRuleEditor from './PrankRuleEditor.jsx';

const format=(seconds)=>{const s=Math.max(0,Math.floor(seconds||0));return `${Math.floor(s/60)}:${String(s%60).padStart(2,'0')}`;};
export default function HQ({onClose}){
  const{catalog,remoteState,viewerTelemetry,injected,injectTitle,triggerPrank,sessionEvents}=useNotflix();
  const[query,setQuery]=useState('');const[selected,setSelected]=useState('pop');const[localLog,setLocalLog]=useState([]);const[localMode,setLocalMode]=useState(false);const[tab,setTab]=useState('live');
  const results=useMemo(()=>catalog.filter((item)=>item.title.toLowerCase().includes(query.toLowerCase())).slice(0,12),[catalog,query]);
  const send=(type,payload,label)=>{if(localMode){if(type==='prank')triggerPrank(payload.id);else if(type==='inject-title')injectTitle(payload.id);else if(type==='player')window.dispatchEvent(new CustomEvent('notflix:remote-player',{detail:payload}));else if(type==='navigate')window.dispatchEvent(new CustomEvent('notflix:remote-navigate',{detail:payload}));}else controlBus.send(type,payload);setLocalLog((prev)=>[{at:Date.now(),label},...prev].slice(0,20));};
  const tele=viewerTelemetry;
  const events=[...localLog,...sessionEvents].sort((a,b)=>(b.at||0)-(a.at||0)).slice(0,30);
  return <div className="hq"><header className="hq__header"><div><Brand compact/><span className="hq__badge">HQ</span></div><div className="hq__status"><span className={`status-dot ${remoteState.connected?'status-dot--live':''}`}/>{remoteState.connected?'TV link active':'Local control ready'}</div><FocusButton className="close-button close-button--static" onClick={onClose}><X/></FocusButton></header>
    <div className="hq__layout"><aside className="hq__sidebar"><FocusButton className={`hq-tab ${tab==='live'?'hq-tab--active':''}`} onClick={()=>setTab('live')}><Activity/> Live Control</FocusButton><FocusButton className={`hq-tab ${tab==='catalog'?'hq-tab--active':''}`} onClick={()=>setTab('catalog')}><Clapperboard/> Catalog Studio</FocusButton><FocusButton className={`hq-tab ${tab==='rules'?'hq-tab--active':''}`} onClick={()=>setTab('rules')}><Sparkles/> Prank Rules</FocusButton><FocusButton className={`hq-tab ${tab==='viewer'?'hq-tab--active':''}`} onClick={()=>setTab('viewer')}><Eye/> Viewer State</FocusButton><div className="hq__mode"><label><input type="checkbox" checked={localMode} onChange={(e)=>setLocalMode(e.target.checked)}/> Control this tab</label><small>Off sends commands through the NOTFLIX control channel to another browser/TV.</small></div></aside>
      <main className="hq__main">{tab==='live'&&<><section className="hq-panel hq-panel--viewer"><div className="hq-panel__title"><span><Cast/> Viewer</span><span className="live-pill"><RadioTower/> LIVE</span></div><div className="viewer-mock"><div className="viewer-mock__screen">{tele?.playing?'PLAYING':'NOTFLIX TV'}<div className="scanline"/></div><div><strong>{tele?.title??'Waiting for TV telemetry'}</strong><span>{tele?.episode?`${tele.episode} · `:''}{tele?`${format(tele.time)} / ${format(tele.total)} · ${Math.round((tele.progress||0)*100)}% · ${tele.profile}`:'Open a title on the viewer device and live playback state appears here.'}</span></div></div>{tele&&<div className="hq-progress"><span style={{width:`${Math.round((tele.progress||0)*100)}%`}}/></div>}<div className="transport"><FocusButton onClick={()=>send('player',{action:'seek-back'},'Seek back 10s')}><SkipBack/></FocusButton><FocusButton onClick={()=>send('player',{action:'play'},'Play')}><Play fill="white"/></FocusButton><FocusButton onClick={()=>send('player',{action:'pause'},'Pause')}><Pause fill="white"/></FocusButton><FocusButton onClick={()=>send('player',{action:'seek-forward'},'Seek forward 10s')}><SkipForward/></FocusButton></div></section><section className="hq-panel"><div className="hq-panel__title"><span><Sparkles/> Instant Pranks</span></div><div className="prank-grid">{Object.entries(PRANKS).map(([id,prank])=><FocusButton key={id} className={`prank-trigger prank-trigger--${prank.kind}`} onClick={()=>send('prank',{id},`Triggered ${prank.title}`)}><strong>{prank.title}</strong><span>{prank.body}</span></FocusButton>)}</div></section></>}
      {tab==='catalog'&&<><section className="hq-panel"><ContentStudio/></section><section className="hq-panel"><div className="hq-panel__title"><span><Clapperboard/> Inject Existing Title</span></div><div className="hq-search"><Search/><input value={query} onChange={(e)=>setQuery(e.target.value)} placeholder="Search catalog"/></div><div className="hq-catalog-list">{results.map((item)=><label className={`hq-title-row ${selected===item.id?'hq-title-row--selected':''}`} key={item.id}><input type="radio" name="title" checked={selected===item.id} onChange={()=>setSelected(item.id)}/><span>{item.emoji}</span><strong>{item.title}</strong><small>{injected.includes(item.id)?'INJECTED':item.custom?'CUSTOM':item.type.toUpperCase()}</small></label>)}</div><FocusButton className="hq-send" onClick={()=>send('inject-title',{id:selected},`Injected ${catalog.find((x)=>x.id===selected)?.title??selected}`)}><Send size={18}/> Inject into TV</FocusButton></section></>}
      {tab==='rules'&&<section className="hq-panel"><PrankRuleEditor/></section>}
      {tab==='viewer'&&<section className="hq-panel"><div className="hq-panel__title"><span><Eye/> Viewer + Event Log</span></div><div className="viewer-state-grid"><div><small>Profile</small><strong>{tele?.profile||'—'}</strong></div><div><small>Title</small><strong>{tele?.title||'—'}</strong></div><div><small>Position</small><strong>{tele?format(tele.time):'—'}</strong></div><div><small>Playback</small><strong>{tele?.playing?'Playing':'Paused / idle'}</strong></div></div><div className="event-log">{events.length?events.map((entry,i)=><div key={`${entry.at}-${i}`}><time>{new Date(entry.at).toLocaleTimeString()}</time><span>{entry.label}</span></div>):<p>No commands yet. The television remains tragically unconfused.</p>}</div></section>}
      </main></div></div>;
}
