import React,{useMemo,useState} from 'react';
import {Activity,Cast,Clapperboard,Eye,Gauge,Pause,Play,RadioTower,RotateCcw,Search,Send,SkipBack,SkipForward,Sparkles,WandSparkles,X} from 'lucide-react';
import {controlBus} from '../lib/controlBus.js';
import {PRANKS} from '../lib/prankEngine.js';
import {useNotflix} from '../context/NotflixContext.jsx';
import Brand from './Brand.jsx';
import FocusButton from './FocusButton.jsx';
import ContentStudio from './ContentStudio.jsx';
import PrankRuleEditor from './PrankRuleEditor.jsx';

const format=(seconds)=>{const s=Math.max(0,Math.floor(seconds||0));const h=Math.floor(s/3600),m=Math.floor((s%3600)/60),sec=s%60;return h?`${h}:${String(m).padStart(2,'0')}:${String(sec).padStart(2,'0')}`:`${m}:${String(sec).padStart(2,'0')}`;};
export default function HQ({onClose}){
  const{catalog,remoteState,viewerTelemetry,injected,injectTitle,triggerPrank,sessionEvents,prankState,resetPrankEffects}=useNotflix();
  const[query,setQuery]=useState('');const[selected,setSelected]=useState('pop');const[localLog,setLocalLog]=useState([]);const[localMode,setLocalMode]=useState(false);const[tab,setTab]=useState('live');const[subtitle,setSubtitle]=useState('This subtitle was definitely not approved by the director.');const[notice,setNotice]=useState('Routine maintenance is complete. Nothing was maintained.');const[swapTarget,setSwapTarget]=useState('gums');
  const results=useMemo(()=>catalog.filter((item)=>item.title.toLowerCase().includes(query.toLowerCase())).slice(0,12),[catalog,query]);
  const health=useMemo(()=>{const total=Math.max(1,catalog.length);const count=(key)=>catalog.filter((item)=>Boolean(item.media?.[key])).length;const posters=count('poster'),backdrops=count('backdrop'),trailers=count('trailer'),full=count('source'),shows=catalog.filter((item)=>item.type==='show').length,custom=catalog.filter((item)=>item.custom).length;return{total,posters,backdrops,trailers,full,shows,custom,generatedPoster:total-posters,generatedBackdrop:total-backdrops,generatedTrailer:total-trailers,generatedFeature:total-full};},[catalog]);
  const send=(type,payload,label)=>{if(localMode){if(type==='prank')triggerPrank(payload.id,payload.overrides);else if(type==='inject-title')injectTitle(payload.id);else if(type==='player')window.dispatchEvent(new CustomEvent('notflix:remote-player',{detail:payload}));else if(type==='navigate')window.dispatchEvent(new CustomEvent('notflix:remote-navigate',{detail:payload}));}else controlBus.send(type,payload);setLocalLog((prev)=>[{at:Date.now(),label},...prev].slice(0,30));};
  const tele=viewerTelemetry;const events=[...localLog,...sessionEvents].sort((a,b)=>(b.at||0)-(a.at||0)).slice(0,30);
  const customPrank=(id,overrides,label)=>send('prank',{id,overrides},label);
  const activeEffects=[prankState.recommendationRow&&'Hijacked recommendations',Object.keys(prankState.ghostProgress||{}).length&&'Haunted Continue Watching',prankState.matchMode&&'Impossible match scores',prankState.fakePlan&&`Fake plan: ${prankState.fakePlan}`,prankState.customSubtitle&&'Subtitle takeover',prankState.qualityMode&&'Quality sabotage',prankState.serviceNotice&&'Service notice',prankState.stillWatching&&'Presence trap'].filter(Boolean);
  return <div className="hq"><header className="hq__header"><div><Brand compact/><span className="hq__badge">HQ</span></div><div className="hq__status"><span className={`status-dot ${remoteState.connected?'status-dot--live':''}`}/>{remoteState.connected?'TV link active':'Local control ready'}</div><FocusButton className="close-button close-button--static" onClick={onClose}><X/></FocusButton></header>
    <div className="hq__layout"><aside className="hq__sidebar"><FocusButton className={`hq-tab ${tab==='live'?'hq-tab--active':''}`} onClick={()=>setTab('live')}><Activity/> Live Control</FocusButton><FocusButton className={`hq-tab ${tab==='catalog'?'hq-tab--active':''}`} onClick={()=>setTab('catalog')}><Clapperboard/> Catalog Studio</FocusButton><FocusButton className={`hq-tab ${tab==='rules'?'hq-tab--active':''}`} onClick={()=>setTab('rules')}><Sparkles/> Prank Rules</FocusButton><FocusButton className={`hq-tab ${tab==='viewer'?'hq-tab--active':''}`} onClick={()=>setTab('viewer')}><Eye/> Viewer State</FocusButton><FocusButton className={`hq-tab ${tab==='health'?'hq-tab--active':''}`} onClick={()=>setTab('health')}><Gauge/> System Health</FocusButton><div className="hq__mode"><label><input type="checkbox" checked={localMode} onChange={(e)=>setLocalMode(e.target.checked)}/> Control this tab</label><small>Off sends commands through the NOTFLIX control channel to another browser/TV.</small></div></aside>
      <main className="hq__main">{tab==='live'&&<><section className="hq-panel hq-panel--viewer"><div className="hq-panel__title"><span><Cast/> Viewer</span><span className="live-pill"><RadioTower/> LIVE</span></div><div className="viewer-mock"><div className="viewer-mock__screen">{tele?.playing?'PLAYING':'NOTFLIX TV'}<div className="scanline"/></div><div><strong>{tele?.title??'Waiting for TV telemetry'}</strong><span>{tele?.episode?`${tele.episode} · `:''}{tele?`${format(tele.time)} / ${format(tele.total)} · ${Math.round((tele.progress||0)*100)}% · ${tele.profile} · ${(tele.media||'generated').toUpperCase()} · ${(tele.quality||'normal').toUpperCase()}`:'Open a title on the viewer device and live playback state appears here.'}</span></div></div>{tele&&<div className="hq-progress"><span style={{width:`${Math.round((tele.progress||0)*100)}%`}}/></div>}<div className="transport"><FocusButton onClick={()=>send('player',{action:'seek-back'},'Seek back 10s')}><SkipBack/></FocusButton><FocusButton onClick={()=>send('player',{action:'play'},'Play')}><Play fill="white"/></FocusButton><FocusButton onClick={()=>send('player',{action:'pause'},'Pause')}><Pause fill="white"/></FocusButton><FocusButton onClick={()=>send('player',{action:'seek-forward'},'Seek forward 10s')}><SkipForward/></FocusButton></div></section>
      <section className="hq-panel"><div className="hq-panel__title"><span><Sparkles/> Instant Prank Arsenal</span><span className="health-grade">{Object.keys(PRANKS).length} EFFECTS</span></div><div className="prank-grid">{Object.entries(PRANKS).map(([id,prank])=><FocusButton key={id} className={`prank-trigger prank-trigger--${prank.kind}`} onClick={()=>send('prank',{id},`Triggered ${prank.title}`)}><strong>{prank.title}</strong><span>{prank.body}</span><small>{prank.effect?prank.effect.replaceAll('-',' '):'modal prank'}</small></FocusButton>)}</div></section>
      <section className="hq-panel"><div className="hq-panel__title"><span><WandSparkles/> Prank Lab</span></div><div className="prank-lab-grid"><label><span>Custom subtitle takeover</span><input value={subtitle} onChange={(e)=>setSubtitle(e.target.value)} maxLength={180}/><FocusButton className="hq-send" onClick={()=>customPrank('subtitleTakeover',{payload:{message:subtitle}},'Custom subtitle takeover')}>Send subtitle</FocusButton></label><label><span>Custom service notice</span><input value={notice} onChange={(e)=>setNotice(e.target.value)} maxLength={180}/><FocusButton className="hq-send" onClick={()=>customPrank('serviceNotice',{payload:{message:notice}},'Custom service notice')}>Broadcast notice</FocusButton></label><label><span>Swap the playing title to</span><select value={swapTarget} onChange={(e)=>setSwapTarget(e.target.value)}>{catalog.filter((item)=>item.type==='movie').map((item)=><option key={item.id} value={item.id}>{item.title}</option>)}</select><FocusButton className="hq-send" onClick={()=>customPrank('contentSwap',{payload:{targetId:swapTarget}},`Swap player to ${catalog.find((x)=>x.id===swapTarget)?.title||swapTarget}`)}>Swap mid-watch</FocusButton></label></div>{activeEffects.length>0&&<div className="active-prank-effects"><strong>Persistent effects currently active</strong><div>{activeEffects.map((effect)=><span key={effect}>{effect}</span>)}</div></div>}<FocusButton className="settings-action prank-reset" onClick={resetPrankEffects}><RotateCcw size={17}/> Reset every persistent prank effect</FocusButton></section></>}
      {tab==='catalog'&&<><section className="hq-panel"><ContentStudio/></section><section className="hq-panel"><div className="hq-panel__title"><span><Clapperboard/> Inject Existing Title</span></div><div className="hq-search"><Search/><input value={query} onChange={(e)=>setQuery(e.target.value)} placeholder="Search catalog"/></div><div className="hq-catalog-list">{results.map((item)=><label className={`hq-title-row ${selected===item.id?'hq-title-row--selected':''}`} key={item.id}><input type="radio" name="title" checked={selected===item.id} onChange={()=>setSelected(item.id)}/><span>{item.emoji}</span><strong>{item.title}</strong><small>{injected.includes(item.id)?'INJECTED':item.custom?'CUSTOM':item.type.toUpperCase()}</small></label>)}</div><FocusButton className="hq-send" onClick={()=>send('inject-title',{id:selected},`Injected ${catalog.find((x)=>x.id===selected)?.title??selected}`)}><Send size={18}/> Inject into TV</FocusButton></section></>}
      {tab==='rules'&&<section className="hq-panel"><PrankRuleEditor/></section>}
      {tab==='viewer'&&<section className="hq-panel"><div className="hq-panel__title"><span><Eye/> Viewer + Event Log</span></div><div className="viewer-state-grid"><div><small>Profile</small><strong>{tele?.profile||'—'}</strong></div><div><small>Title</small><strong>{tele?.title||'—'}</strong></div><div><small>Position</small><strong>{tele?format(tele.time):'—'}</strong></div><div><small>Playback</small><strong>{tele?.buffering?'Buffering prank':tele?.playing?'Playing':'Paused / idle'}</strong></div></div><div className="event-log">{events.length?events.map((entry,i)=><div key={`${entry.at}-${i}`}><time>{new Date(entry.at).toLocaleTimeString()}</time><span>{entry.label}</span></div>):<p>No commands yet. The television remains tragically unconfused.</p>}</div></section>}
      {tab==='health'&&<section className="hq-panel health-panel"><div className="hq-panel__title"><span><Gauge/> NOTFLIX Readiness</span><span className="health-grade">PRANK COMPLETE</span></div><p className="health-lede">The platform and prank engine are complete. Every title has generated playback and artwork fallbacks, every prank can be fired manually, and every prank can be attached to playback events. The remaining upgrade is replacing generated media with finished movie artwork and films.</p><div className="health-grid"><div><small>Catalog</small><strong>{health.total}</strong><span>playable titles</span></div><div><small>Pranks</small><strong>{Object.keys(PRANKS).length}</strong><span>built-in effects</span></div><div><small>TV link</small><strong>{remoteState.connected?'LIVE':'LOCAL'}</strong><span>{remoteState.connected?'controller connected':'ready for connection'}</span></div><div><small>Coverage</small><strong>100%</strong><span>generated or custom</span></div></div><div className="health-meter"><div><span>Playable-media coverage</span><strong>100%</strong></div><div className="health-meter__track"><span style={{width:'100%'}}/></div></div><div className="health-assets"><div><strong>{health.posters} + {health.generatedPoster}</strong><span>Custom + generated posters</span></div><div><strong>{health.backdrops} + {health.generatedBackdrop}</strong><span>Custom + generated backdrops</span></div><div><strong>{health.trailers} + {health.generatedTrailer}</strong><span>Custom + generated trailers</span></div><div><strong>{health.full} + {health.generatedFeature}</strong><span>Custom + generated features</span></div></div><div className="health-checks"><span>✓ Premium pause / rewind</span><span>✓ Real buffer-loop sabotage</span><span>✓ Fake errors + service notices</span><span>✓ Subtitle takeover</span><span>✓ Quality downgrade</span><span>✓ Impossible match scores</span><span>✓ Recommendation hijacking</span><span>✓ Haunted Continue Watching</span><span>✓ Fake subscription tier</span><span>✓ Mid-watch title swap</span><span>✓ Surprise episode injection</span><span>✓ Still-watching trap</span><span>✓ Chained prank sequence</span><span>✓ Per-title event rules</span><span>✓ HQ remote control</span><span>✓ TV navigation + playback</span></div></section>}
      </main></div></div>;
}
