import React,{useState} from 'react';
import {Pencil,Plus,Check,Trash2,X,LockKeyhole} from 'lucide-react';
import {useNotflix} from '../context/NotflixContext.jsx';
import {maturityLabel,policyForProfile} from '../lib/profilePolicy.js';
import Brand from './Brand.jsx'; import FocusButton from './FocusButton.jsx';

const avatarChoices=['😎','🧢','👾','🦖','🚀','🎈','🦈','🧠','🍿','🎮'];
export default function ProfilePicker(){
  const{profiles,setProfiles,selectProfile}=useNotflix();const[manage,setManage]=useState(false);const[editing,setEditing]=useState(null);
  const profile=profiles.find((p)=>p.id===editing);const profilePolicy=profile?policyForProfile(profile.id):null;
  const update=(id,patch)=>setProfiles((prev)=>prev.map((p)=>p.id===id?{...p,...patch}:p));
  const remove=(id)=>{if(profiles.length<=1||policyForProfile(id)?.locked)return;setProfiles((prev)=>prev.filter((p)=>p.id!==id));setEditing(null);};
  const add=()=>{if(profiles.length>=5)return;const id=`profile-${Date.now()}`;setProfiles((prev)=>[...prev,{id,name:'New Profile',avatar:'🙂',color:'#555',maturity:'all',autoplay:true}]);setManage(true);setEditing(id);};
  return <main className="profiles-screen"><header className="profiles-screen__header"><Brand/></header><section className="profiles-panel"><h1>{manage?'Manage Profiles':'Who’s watching?'}</h1><div className="profile-grid">{profiles.map((item)=><div className="profile-wrap" key={item.id}><FocusButton className="profile-card" onClick={()=>manage?setEditing(item.id):selectProfile(item.id)} aria-label={`${manage?'Edit':'Open'} ${item.name}`}><span className="profile-card__avatar" style={{background:`linear-gradient(145deg, ${item.color}, #101010)`}}><span>{item.avatar}</span>{manage&&<span className="profile-card__edit"><Pencil size={22}/></span>}</span><span className="profile-card__name">{item.name}</span><small className="profile-card__limit">{maturityLabel(item.maturity)}</small></FocusButton></div>)}{profiles.length<5&&<FocusButton className="profile-card profile-card--add" onClick={add}><span className="profile-card__avatar profile-card__avatar--add"><Plus size={58}/></span><span className="profile-card__name">Add Profile</span></FocusButton>}</div>{manage&&profile&&<div className="profile-manage-card"><div className="profile-manage-card__avatar">{profile.avatar}</div><div className="profile-manage-card__fields"><label><span>Name</span><input value={profile.name} disabled={Boolean(profilePolicy?.locked)} onChange={(e)=>update(profile.id,{name:e.target.value.slice(0,18)})}/></label><label><span>Avatar</span><select value={profile.avatar} onChange={(e)=>update(profile.id,{avatar:e.target.value})}>{avatarChoices.map((avatar)=><option key={avatar} value={avatar}>{avatar}</option>)}</select></label><label><span>Allowed maturity</span><select value={profile.maturity} disabled={Boolean(profilePolicy?.locked)} onChange={(e)=>update(profile.id,{maturity:e.target.value})}><option value="all">All catalog titles</option><option value="pg13">Up to PG-13 / TV-14</option><option value="pg">Up to PG / TV-PG</option></select></label>{profilePolicy?.locked&&<div className="profile-policy-note"><LockKeyhole size={16}/><span>Household limit locked: {profilePolicy.label}</span></div>}<label className="profile-checkbox"><input type="checkbox" checked={profile.autoplay!==false} onChange={(e)=>update(profile.id,{autoplay:e.target.checked})}/><span>Autoplay previews</span></label></div><div className="profile-manage-card__actions"><FocusButton className="settings-action" onClick={()=>setEditing(null)}><Check size={17}/> Done</FocusButton>{profiles.length>1&&!profilePolicy?.locked&&<FocusButton className="settings-action settings-action--danger" onClick={()=>remove(profile.id)}><Trash2 size={17}/> Delete</FocusButton>}<FocusButton className="icon-button" onClick={()=>setEditing(null)} aria-label="Close profile editor"><X/></FocusButton></div></div>}<FocusButton className={`outline-button ${manage?'outline-button--active':''}`} onClick={()=>{setManage((v)=>!v);setEditing(null);}}>{manage?'Done':'Manage Profiles'}</FocusButton></section></main>;
}
