import React,{useEffect,useMemo,useState} from 'react';
import {Plus,Save,Tv2} from 'lucide-react';
import {useNotflix} from '../context/NotflixContext.jsx';
import {slugify} from '../lib/titleFactory.js';
import FocusButton from './FocusButton.jsx';

const blank={season:'1',number:'1',title:'',description:'',duration:'28m',emoji:'📺',source:'',subtitleUrl:'',introEnd:''};
export default function SeriesStudio(){
  const{catalog,updateTitleContent,notify}=useNotflix();
  const shows=useMemo(()=>catalog.filter((item)=>item.type==='show'),[catalog]);
  const[showId,setShowId]=useState(shows[0]?.id||'');const[form,setForm]=useState(blank);
  useEffect(()=>{if(!shows.some((item)=>item.id===showId))setShowId(shows[0]?.id||'');},[shows,showId]);
  const show=shows.find((item)=>item.id===showId);
  const patch=(key,value)=>setForm((prev)=>({...prev,[key]:value}));
  const addEpisode=(event)=>{event.preventDefault();if(!show||!form.title.trim())return;const seasonNumber=Math.max(1,Number(form.season)||1);const episodeNumber=Math.max(1,Number(form.number)||1);const episode={id:`s${seasonNumber}e${episodeNumber}-${slugify(form.title)}`,number:episodeNumber,title:form.title.trim(),description:form.description.trim()||'An episode has appeared in the catalog under suspicious circumstances.',duration:form.duration.trim()||'28m',emoji:form.emoji||show.emoji,tone:show.tone,media:{source:form.source.trim(),subtitles:form.subtitleUrl.trim()?[{lang:'en',label:'English',src:form.subtitleUrl.trim()}]:[],introEnd:Number(form.introEnd)||0}};const seasons=[...(show.seasons||[])].map((season)=>({...season,episodes:[...(season.episodes||[])]}));let season=seasons.find((s)=>s.number===seasonNumber);if(!season){season={number:seasonNumber,episodes:[]};seasons.push(season);}season.episodes=season.episodes.filter((ep)=>ep.number!==episodeNumber);season.episodes.push(episode);season.episodes.sort((a,b)=>a.number-b.number);seasons.sort((a,b)=>a.number-b.number);updateTitleContent(show.id,{seasons});notify(`${show.title}: S${seasonNumber}E${episodeNumber} added`);setForm((prev)=>({...blank,season:String(seasonNumber),number:String(episodeNumber+1)}));};
  return <details className="studio-section"><summary><Tv2 size={16}/> Series / episode builder</summary><div className="series-studio"><label><span>Show</span><select value={showId} onChange={(e)=>setShowId(e.target.value)}>{shows.map((item)=><option key={item.id} value={item.id}>{item.title}</option>)}</select></label>{show?<><div className="season-map">{(show.seasons||[]).map((season)=><div key={season.number}><strong>Season {season.number}</strong><span>{season.episodes?.length||0} episodes</span><small>{season.episodes?.map((ep)=>`${ep.number}. ${ep.title}`).join(' · ')||'No episodes'}</small></div>)}</div><form className="studio-form" onSubmit={addEpisode}><label><span>Season</span><input type="number" min="1" value={form.season} onChange={(e)=>patch('season',e.target.value)}/></label><label><span>Episode #</span><input type="number" min="1" value={form.number} onChange={(e)=>patch('number',e.target.value)}/></label><label><span>Emoji</span><input value={form.emoji} onChange={(e)=>patch('emoji',e.target.value)} maxLength={4}/></label><label className="studio-form__wide"><span>Episode title</span><input value={form.title} onChange={(e)=>patch('title',e.target.value)} placeholder="The Episode That Definitely Existed"/></label><label className="studio-form__wide"><span>Description</span><textarea rows={3} value={form.description} onChange={(e)=>patch('description',e.target.value)}/></label><label><span>Duration</span><input value={form.duration} onChange={(e)=>patch('duration',e.target.value)}/></label><label><span>Intro ends (seconds)</span><input type="number" min="0" value={form.introEnd} onChange={(e)=>patch('introEnd',e.target.value)}/></label><label className="studio-form__wide"><span>Episode video URL</span><input value={form.source} onChange={(e)=>patch('source',e.target.value)} placeholder="https://...mp4"/></label><label className="studio-form__wide"><span>VTT subtitle URL</span><input value={form.subtitleUrl} onChange={(e)=>patch('subtitleUrl',e.target.value)}/></label><FocusButton className="hq-send studio-form__submit" type="submit"><Plus size={17}/><Save size={16}/> Add / replace episode</FocusButton></form></>:<p className="studio-empty">Create a show first, then come back and make television regret having episodes.</p>}</div></details>;
}
