import React,{useEffect,useMemo,useState} from 'react';
import {Check,Play,Plus,ThumbsUp,X} from 'lucide-react';
import {useNotflix} from '../context/NotflixContext.jsx';
import FocusButton from './FocusButton.jsx';
import Artwork from './Artwork.jsx';

export default function TitleModal({item,onClose,onPlay,onOpenTitle}){
  const{myList,toggleMyList,catalog,ratings,rateTitle,progress}=useNotflix();
  const[seasonNumber,setSeasonNumber]=useState(item?.seasons?.[0]?.number??1);
  useEffect(()=>setSeasonNumber(item?.seasons?.[0]?.number??1),[item?.id]);
  const season=item?.seasons?.find((s)=>s.number===seasonNumber);
  const related=useMemo(()=>!item?[]:catalog.filter((candidate)=>candidate.id!==item.id&&candidate.genres.some((g)=>item.genres.includes(g))).slice(0,6),[item,catalog]);
  if(!item)return null;const inList=myList.includes(item.id);const liked=ratings[item.id]==='up';const generated=!item.media?.source;
  return <div className="modal-backdrop" onMouseDown={(e)=>e.target===e.currentTarget&&onClose()}><section className="title-modal" role="dialog" aria-modal="true" aria-label={item.title}>
    <div className="title-modal__hero"><Artwork item={item} variant="backdrop"/><div className="title-modal__fade"/><FocusButton className="close-button" onClick={onClose}><X size={22}/></FocusButton><div className="title-modal__hero-content"><div className="eyebrow">{item.kicker}</div><h2>{item.title}</h2><div className="title-modal__actions"><FocusButton className="hero-button hero-button--play" onClick={()=>onPlay(item)}><Play size={21} fill="currentColor"/> Play</FocusButton><FocusButton className="hero-button hero-button--info" onClick={()=>onPlay(item,null,{trailer:true})}><Play size={18}/> {item.media?.trailer?'Trailer':'Preview'}</FocusButton><FocusButton className="round-button round-button--large" onClick={()=>toggleMyList(item.id)}>{inList?<Check/>:<Plus/>}</FocusButton><FocusButton className={`round-button round-button--large ${liked?'round-button--liked':''}`} onClick={()=>rateTitle(item.id,liked?null:'up')}><ThumbsUp/></FocusButton></div></div></div>
    <div className="title-modal__body"><div className="title-modal__primary"><div className="detail-meta"><strong>{item.match}% Match</strong><span>{item.year}</span><span className="rating-pill">{item.rating}</span><span>{item.runtime}</span><span className="hd-pill">HD</span>{item.custom&&<span className="custom-pill">CUSTOM</span>}{generated&&<span className="custom-pill">MOTION</span>}</div><p className="detail-description">{item.description}</p></div><aside className="title-modal__aside"><p><span>Cast:</span> {item.cast.join(', ')}</p><p><span>Genres:</span> {item.genres.join(', ')}</p><p><span>This title is:</span> Absurd, Suspiciously Polished, Questionable</p></aside>
    {item.type==='show'&&<section className="episodes-section"><div className="episodes-header"><h3>Episodes</h3><label className="season-select-wrap"><select value={seasonNumber} onChange={(e)=>setSeasonNumber(Number(e.target.value))}>{item.seasons.map((s)=><option key={s.number} value={s.number}>Season {s.number}</option>)}</select></label></div><div className="episode-list">{season?.episodes.map((ep)=><FocusButton className="episode-row" key={ep.id} onClick={()=>onPlay(item,{...ep,seasonNumber})}><span className="episode-row__number">{ep.number}</span><span className="episode-row__thumb"><Artwork item={{...item,...ep,title:ep.title,tone:ep.tone??item.tone,emoji:ep.emoji??item.emoji}} variant="episode"/><Play size={22} fill="white"/></span><span className="episode-row__copy"><strong>{ep.title}</strong><span>{ep.description}</span>{progress[`${item.id}:${ep.id}`]>0&&<span className="episode-progress">{Math.round(progress[`${item.id}:${ep.id}`]*100)}% watched</span>}</span><span className="episode-row__duration">{ep.duration}</span></FocusButton>)}</div></section>}
    <section className="trailers-section"><h3>Trailers & More</h3><div className="trailers-grid"><FocusButton className="trailer-card" onClick={()=>onPlay(item,null,{trailer:true})}><Artwork item={item} variant="card"/><span><Play size={16} fill="white"/> {item.media?.trailer?'Official NOTFLIX Trailer':'Generated NOTFLIX Preview'}</span></FocusButton></div></section>
    <section className="more-like-this"><h3>More Like This</h3><div className="more-grid">{related.map((relatedItem)=><FocusButton key={relatedItem.id} className="more-card" onClick={()=>onOpenTitle(relatedItem)}><span className="more-card__art"><Artwork item={relatedItem} variant="card"/><strong>{relatedItem.title}</strong></span><span className="more-card__copy"><span><b>{relatedItem.match}% Match</b> · {relatedItem.rating}</span><p>{relatedItem.description}</p></span></FocusButton>)}</div></section><section className="about-title"><h3>About {item.title}</h3><p><span>Creators:</span> {item.creators.join(', ')}</p><p><span>Genres:</span> {item.genres.join(', ')}</p><p><span>Maturity rating:</span> {item.rating} · Contains scenes of irresponsible decision-making.</p><p><span>Playback:</span> {generated?'Generated NOTFLIX Motion cut with full runtime and cinematic story beats.':'Custom media master.'}</p></section></div>
  </section></div>;
}
